### ISSUE TITLE
Facebook chatbot has stopped working

### ISSUE THREAD

**Issue by emirhartato** [urbanriskmap/cognicity-reports-facebook#18]
Hi all,

We just found out yesterday that the Facebook chatbot has stopped working. 

We're not receiving any replies from the bot.

![image](https://user-images.githubusercontent.com/1563226/47128072-0dad2080-d2ba-11e8-9354-c8e41bec320d.png)

Thank you.

**Comment by matthewberryman** [comment]
* No logging from API GW (this was disabled, but is now enabled).
* Lambda logs read as: 
```Failed calling Send API 400 Bad Request { message: 'Error validating access token: The session has been invalidated because the user changed their password or Facebook has changed the session for security reasons.',
type: 'OAuthException',
code: 190,
error_subcode: 460,
fbtrace_id: 'CO7RWui8O74' }
```
Checking in Facebook it seems they have invalidated the token for security reasons https://www.wired.com/story/facebook-hack-check-if-account-affected/

Actions to be taken (in order):
1. @matthewberryman to regen access tokens for petabencana.id dev and prod (both affected) and set them up in lambdas.
2. @matthewberryman and @emirhartato to test and confirm.
3. @emirhartato to reply to anyone who sent a message to the page but didn't get it back.
4. @abrahamq to check on dev bots for riskmap.in and riskmap.us. I just checked and prod bots for both are still good and working, so this is low priority.

**Comment by emirhartato** [comment]
I've done point 2 and 3. Thank you for the quick fix.

**Comment by matthewberryman** [comment]
@emirhartato thanks for the update. Over to @abrahamq to check on dev bots and then close.

**Comment by abrahamq** [comment]
Hi, all dev bots are working. Thanks for the fast response @matthewberryman . Closing as this seems resolved.
