### ISSUE TITLE
riskmap.in and riskmap.us bots are not deployable from a single branch using this code.

### ISSUE THREAD

**Issue by abrahamq** [urbanriskmap/cognicity-reports-facebook#4]
Need to separate responses out into config files- maybe through the same encrypted files system that we're using currently. 

For example- there are monsoon prep cards in riskmap.in but not in petabencana.id. Currently, the response to clicking the 'get_started' button is baked into the source code, which means that we can't deploy the same source code to both locations. What would be better is separating the response and the source code into different files.

**Comment by talltom** [comment]
This is now fixed using the new NPM module cognicity-bot-core.
